### ISSUE TITLE
[Feature Request] Comprehensive Error Handling

### ISSUE THREAD

**Issue by ncthbrt** [meafmira/bs-axios#14]
There is often a need to be more particular about error handling. As explained in the [Handling Errors](https://github.com/axios/axios#handling-errors) section, Axios allows access to the request/response objects to determine what went wrong. It'd be great if this was a supported feature of bs-axios.

**Comment by meafmira** [comment]
@ncthbrt I've added error handling section to readme. See here:
https://github.com/meafmira/bs-axios#error-handling
