### ISSUE TITLE
How do you access/set defaults?

### ISSUE THREAD

**Issue by thislogancall** [meafmira/bs-axios#24]
Example from JS:
```javascript

 axios.defaults.headers.common["Authorization"] = token
```

Is this possible with the current bindings?

**Comment by meafmira** [comment]
Sure. There is an example https://github.com/meafmira/bs-axios#headers

**Comment by thislogancall** [comment]
@meafmira I did notice that this is how you create headers, but what about updating them in either the axios defaults or on an instance?

**Comment by thislogancall** [comment]
I ended up doing the following where `instance` is an instance of bs-axios:

```reason
let setAxiosAuthWith = [%raw {|
  function(axiosInstance, header) {
   | axiosInstance.defaults.headers["Authorization"] = header 
   | /* axios.defaults.common["Authorization"] = header  */
   }
 |}];
 
let setAxiosAuth = (header: string) => setAxiosAuthWith(instance, header);

```
