### ISSUE TITLE
Change name of labeled arg `method`

### ISSUE THREAD

**Issue by Koleok** [meafmira/bs-axios#6]
It looks like `method` is a reserved keyword in ocaml. 

![image](https://user-images.githubusercontent.com/10928312/35657416-5b0a0e90-06ca-11e8-944a-8b9cdf5aa637.png)

Reason seems to handle this while being compiled to AST and adds a trailing `_`, but it breaks syntax highlighting in the remainder of the file which is kind of annoying.

_with `~method`_
![image](https://user-images.githubusercontent.com/10928312/35657427-64ef5834-06ca-11e8-9201-8c274ebde348.png)

_without `~method`_
![image](https://user-images.githubusercontent.com/10928312/35657436-7b7d9264-06ca-11e8-8089-fc6f493af0ec.png)

I propose just changing the label to `httpMethod` | `verb` | `httpVerb`

open to any other names of course ¯\_(ツ)_/¯

**Comment by meafmira** [comment]
@Koleok nope. I fixed this here https://github.com/meafmira/bs-axios/commit/33839405cca26fdd2314df634e4ef1762857c6c6

Thank you!

**Comment by Koleok** [comment]
Ahhh ✨ ❤️ awesome
